[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1tDUv02fWk7kwTy9-WrPdpCgqE24xPAkNp4jDpBHbIWI"

[google_credentials2]
type = "service_account"
project_id = "api-completo"
private_key_id = "de00dd6d59eb122e55118d27c0d985edce1c3b25"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCe0nl44t+y7P1e
/ultfClDrQshMf0G1dxDlO8/EhAZZ44MyhxGc8BmSIwt2pF/TJsMLTVMCj7f14Yq
XaEzrfEGNdK85IaGfS1b0RWCBgS/d+fDOHz4W6T+Zx61Vmo9d7cLje7jxg63dztB
+oAF7PfuyfedRnfjYhXfaW0X4DN52cJMVmzZk976OdtzvJvGXg1fUxb5tg+U60hk
XzU8z5u4vT2DyNPfdh/Njavsh9HUjk3yIAf5VaCCq9heFLKrleNKjEw+db78DDCS
LOSAtOABjv7fGKdwGPGKnVXK5bOzAXFSF0kLa6+9HnDPtRRrnSgzIWsl7Oy4NgN2
YfDjMaRTAgMBAAECggEACxmx1MGimepXcR7G6NiPN8Qt7XWFdkdXPD/6EsHr7yKe
OoWbwU7QyTVT2taWabvMcGbufTCQIWv6XBasMCT9ng3/+yTLxDWWiH7ODobmKQ2z
3KCjl2YsW32Ql2MBTOeDmyKh6jiLCcajFSLxdLiRwZZLIKpusa1G0xUWw17vqhny
WbSTwdTXTiSxDup+MgBV+prj2MeKvKHnpAZeVG2K7j0qxPLfa0FO1nybxKCEka4C
7T3oInhMzenrOq96os0zjX+zXnB32HNkjfvW4FHYLUOh9CycMl7/Iz3afeGIrTZu
7LYxrc3MRoJ0Q9kGhL2/ydMXzxZL3YhliYBRY6w8KQKBgQDeEvDYVCJltxUkcF0Z
mWgVtdstRME8F6wi2CDG8oZpXc5Ns/ziuMCXpbYzxPhFF1U5lmj/ujgHGQCLlVuJ
A7weK7N+nhw61pKYC49P//DWv29teIXqhEHhQdeYrR+/2egnvHEonKHgGISYwfYR
MC8t6Pg/65JCwyGzSsksuMttCQKBgQC3FdPS0JSl8kzN1n3EJyyvF+J32e7mpkLn
ZzBa2ibOC+aUtL0G6bGH1O7mjN8nHyoC70WAG4u9yN0d+JvNkA0Ob5CEoJw7Wvm4
pBpcPeHTQ2tejWmcXe1Hbvkdn6h3wq5dKmQgtlsI1Am39Nv4fI2qR8OjjA7hhUlZ
Fx8aEVN5ewKBgQCEZYZxcrePLLfOIa9fs7X6O5GQS41o5jQaEgB4m97GssZsTQJX
qQ4pWwJlmujpSB/nVWUEEWGV2bIZhdIsva1Jz4QT2O+7pHGBdGLcrxpG7ZrhCRnN
10vvn/GJdK2ZE7D0/8P3Emrvz6495GVvmeqG1H4snaV1aCCPY+bMYt/lAQKBgQCj
A1xHKFAyMTsRSxlPvVGb1Lhf3jtIQmDviIEVY4eJji8P2J01un3HY2ATBvrp6mWN
l11aYyxZHq9CMEkJDmmRoOQcMqTodGhEbljKKI8Ze73twht2jmrmX3iPV8i4WS7G
5SehuLv1cFX25J228a9xHdSjmeDmC7bzDBM1MpgQYQKBgQDS+Tdz2Lx7J136/I5g
W/PaWuLEMbG9ErO47i0J8mwmL7UbpgFkCaf5zXKlnbhDpg8GsxOCx8Y06x0oxEor
YL+w/kn4vTSESzL0MqNRmRLtLeoZVOh3j/q+MJqhbAl0kEXedoQAW3bYf5asgnEE
b7DciC6nvwsiLGqT59jT3775Nw==
-----END PRIVATE KEY-----"""
client_email = "api-completo@api-completo.iam.gserviceaccount.com"
client_id = "100790462433022167493"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/api-completo%40api-completo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

